
GET http://localhost:3000/productos

### ver por id
GET http://localhost:3000/productos/10

###  borrar por id
DELETE  http://localhost:3000/productos/5

### crear nuevo producto
POST http://localhost:3000/productos/create
Content-Type: application/json

{
    "nombre": "Cafe Candelas",
    "formato": "CAJA 24U",
    "cantidad": "",
    "precioSin": "",
    "iva": "",
    "precioCon": "",
    "fk_restaurante": "",
    "fk_categoria":""
}

### actualizar db
PUT http://localhost:3000/productos
Content-Type: application/json

{
    "id": 8,
    "nombre": "PERRa Chica",
    "formato": "CAJA 24U",
    "cantidad": "",
    "precioSin": "",
    "iva": "",
    "precioCon": "",
    "fk_restaurante_id": null,
    "fk_categoria_id":null
}