### login

POST http://localhost:3000/usuarios/login
Content-Type: application/json 

{
    "email": "mario@gmail.com",
    "password": "12345"
}


### usuarios

### negocios de un usuario
GET http://localhost:3000/usuarios/negocios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvRW1haWwiOiJtYXJpb0BnbWFpbC5jb20iLCJjcmVhdGVkQXQiOjE2MzE3MTIyMDQsImV4cGlyZWRBdCI6MTYzMTcyNDIwNCwiaWF0IjoxNjMxNzEyMjA0fQ.ypVaqpbt5OS5JV7LYR09ACj-itwFFUnWzJCagaFI8IQ


### crear usuario
POST  http://localhost:3000/usuarios/registro
Content-Type: application/json

{
    "nombre": "Rubén",
    "apellidos": "Fernan",
    "username": "ruben",
    "email" : "rubenlagoart@gmail.com",
    "password":  "rubenL.3",
    "telefono": "612312312"
}

### borrar usuario
DELETE http://localhost:3000/usuarios/borrar/13



### productos

GET http://localhost:3000/productos

### ver por id
GET http://localhost:3000/productos/10

###  borrar por id
DELETE  http://localhost:3000/productos/5

### crear nuevo producto
POST http://localhost:3000/productos/create
Content-Type: application/json

{
    "nombre": "Cafe Candelas",
    "formato": "CAJA 24U",
    "cantidad": "",
    "precioSin": "",
    "iva": "",
    "precioCon": "",
    "fk_restaurante": "",
    "fk_categoria":""
}

### editar db
PUT http://localhost:3000/productos/
Content-Type: application/json

{
    "id": 8,
    "nombre": "PERRa puta",
    "formato": "CAJA 24U",
    "cantidad": "",
    "precioSin": "",
    "iva": "",
    "precioCon": "",
    "fk_restaurante_id": null,
    "fk_categoria_id":null
}

###

GET http://localhost:3000/categorias

###

POST  http://localhost:3000/categorias/create
Content-Type: application/json

{
 "nombre": "Infusiones"
}
###

DELETE  http://localhost:3000/categorias/3

###

GET http://localhost:3000/categorias/2

###

PUT http://localhost:3000/categorias/2
Content-Type: application/json

{
    "nombre": "Enoteca"
}

###

GET http://localhost:3000/productos/negocios/4
